### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by dc1rdb** [Kragrathea/TelloLib#5]
Samsung S3 (GT-I9305), running LineageOS 14.1 (Android 7.1.2):
There are two conditions where video is not working:
1) after return from "Settings" menu if the drone was already connected and video feed was established
2) randomly on startup

Closing the app through Android task manager and restarting it solves the problem. Sometimes a few attempts are required.

**Comment by dc1rdb** [comment]
Samsung S4 (GT-I9505), running LineageOS 14.1 (Android 7.1.2):

Video not working only after return from "Settings" menu.

**Comment by Kragrathea** [comment]
On the S4 does the video come back after going to task manager?

**Comment by dc1rdb** [comment]
On the S4, the video comes back after closing the app through Android task manager and restarting it.

**Comment by dc1rdb** [comment]
With version 0.6, the video problem is completely gone on the Samsung S4 (GT-I9505).
