### ISSUE TITLE
TelloConsole video not working

### ISSUE THREAD

**Issue by daanzu** [Kragrathea/TelloLib#9]
I'm trying to use TelloLib on PC, but can't get the video working. Tello.onVideoData never gets called. Normal controls & flight data work fine. Ideas?

**Comment by daanzu** [comment]
Nevermind; fixed: firewall issues. Library works great!

**Comment by mojto** [comment]
> Nevermind; fixed: firewall issues. Library works great!

I have the same problem, how did you solve it?

**Comment by daanzu** [comment]
@mojto Look in Windows' firewall settings and make sure the executable you're running has authority to open the necessary ports, on public/private networks.

**Comment by mojto** [comment]
> @mojto Look in Windows' firewall settings and make sure the executable you're running has authority to open the necessary ports, on public/private networks.

Yes, My app is allowed on both public and private networks. 
But when I run the "TelloConsole" in Visual Studio, there is no window for video streaming and just a console which prints the parameters and status of the drone is shown. 
Did you modify the code in TelloConsole?
